/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Chunking / assembly / retrieval options for the `Document.from*` constructors.
 * Every field is optional; omit for evidence-backed defaults.
 */
export interface Options {
  /** Source label for `fromText` (default `"document"`). */
  source?: string
  /** Target tokens per chunk (index-time). Default 128. */
  chunkSize?: number
  /** Sentences of overlap between adjacent chunks. Default 1. */
  chunkOverlap?: number
  /** Default assembly token budget (override per call). Default 8192. */
  tokenBudget?: number
  /** Candidates to retrieve before assembly. Default 20. */
  candidateK?: number
  /**
   * Assembly strategy: `auto` (default) · `reasoning_preserving` ·
   * `distractor_filtered` · `redundancy_pruned` · `max_density` · `raw_topk`.
   */
  strategy?: string
  /** `"lexical"` (default, BM25), `"hybrid"`, or `"semantic"`. */
  retrieval?: string
  /** Built-in embedding model to download (`"bge-small"` / `"bge-base"`). */
  model?: string
  /** Advanced: path to a local ONNX embedding model. */
  embedderModel?: string
  /** Advanced: path to its tokenizer. */
  embedderTokenizer?: string
  /** Advanced: the model's output dimension. Default 384. */
  embedderDim?: number
  /** Advanced: `"cls"` (default) or `"mean"`. */
  embedderPooling?: string
  /** Advanced: query prefix for asymmetric models (E5: `"query: "`). */
  embedderQueryPrefix?: string
  /** Advanced: passage prefix for asymmetric models (E5: `"passage: "`). */
  embedderPassagePrefix?: string
  /** Hybrid BM25 prune depth. Default 50. */
  candidatePool?: number
  /**
   * Optional second-stage cross-encoder reranker by name (`"cross-encoder"`,
   * auto-downloaded). Reorders the candidate pool by jointly scoring each
   * `(query, passage)` pair. Works under any retrieval tier.
   */
  rerank?: string
  /**
   * Floor on the number of candidates delivered to the assembler. Under
   * `"hybrid"` / `"semantic"` retrieval, if the primary tier returns
   * fewer, a BM25 fallback tops the result up to this number. Default
   * `0` (off). No effect under `"lexical"`. Pair with
   * `report.lowConfidenceRetrieval` to detect a weak-fallback case.
   */
  minCandidates?: number
  /**
   * Lexical analyzer language. Drives both BM25 retrieval and the
   * grounding scorer's term extraction so the two layers agree on what
   * counts as "the same term" (English `compression` finds `compress`,
   * German `Bücher` finds `Buch`, etc.). Default `"english"`.
   *
   * Supported: `"arabic"`, `"danish"`, `"dutch"`, `"english"`,
   * `"finnish"`, `"french"`, `"german"`, `"greek"`, `"hungarian"`,
   * `"italian"`, `"norwegian"`, `"portuguese"`, `"romanian"`,
   * `"russian"`, `"spanish"`, `"swedish"`, `"tamil"`, `"turkish"` —
   * the 18 Snowball Porter2 languages. Unknown strings ERROR (no
   * silent fallback to English; a typo'd `"germann"` surfaces).
   */
  language?: string
  /**
   * Preserve source-document order of selected chunks instead of the
   * strategy's relevance order. Useful for chat histories / transcripts
   * where chronology matters. Default `false`. See
   * `crates/examples/examples/chat_rag.rs` for the worked pattern.
   */
  preserveOrder?: boolean
  /**
   * When `Document.context(query)` retrieves a chunk classified as code
   * (`metadata.kind === "code"`), auto-pull this many adjacent chunks
   * (i±1, … in the same file) so the implementation body arrives with
   * the signature. Default `1`; pass `0` to disable. See
   * `docs/findings/CODE_NEIGHBORS_DEFAULT.md` for the measured tradeoff.
   */
  codeNeighborsDefault?: number
  /**
   * When `Document.context(query)` retrieves a prose chunk with a
   * `metadata.heading`, auto-attach the section's heading chunk for
   * context. Default `true`. See
   * `docs/findings/PROSE_HEADING_DEFAULT.md` for the measurement.
   */
  proseHeadingDefault?: boolean
}
/** Extra options for `Document.fromFolder` (plus the chunking/retrieval `options`). */
export interface FolderOptions {
  /** Recurse into subdirectories. Default true. */
  recursive?: boolean
  /** Honor `.gitignore`. Default true. */
  gitignore?: boolean
  /** Extra gitignore-style globs to exclude, e.g. `["*.lock", "tests/**"]`. */
  ignore?: Array<string>
  /** Persist the index to disk and reload it incrementally on the next run. */
  persist?: boolean
  /** Where the persisted index lives (default `<folder>/.redhop`). */
  indexDir?: string
  /** Chunking / retrieval options (same fields as the other constructors). */
  options?: Options
}
/** Where one selected chunk came from — for citing the evidence. */
export interface Citation {
  source: string
  page?: number
  heading?: string
  line?: number
  text: string
}
/** The Decision Report: what the assembly did, and why. */
export interface Report {
  /**
   * The strategy actually used — the resolved concrete strategy after
   * `auto` (if requested) was decided. One of `"raw_topk"`,
   * `"distractor_filtered"`, `"redundancy_pruned"`, `"max_density"`,
   * `"reasoning_preserving"`. Never `"auto"` (Auto is always resolved
   * before assembly).
   */
  strategy: string
  /**
   * What the caller requested — may be `"auto"`. Differs from `strategy`
   * when the Auto policy resolved to a concrete action.
   */
  requestedStrategy: string
  /** `"passthrough"` | `"prune"` | `"not_auto"`. */
  autoDecision: string
  /** Total tokens in the input (retrieved) set, before assembly. */
  inputTokens: number
  /** The token-budget cap applied during assembly. */
  tokenBudget: number
  totalTokens: number
  /** `total_tokens / token_budget` — how much of the budget was used. */
  tokenUtilization: number
  /** How many chunks were in the input (retrieved) set. */
  nInputChunks: number
  /** How many chunks survived assembly into the final context. */
  nSelected: number
  /** Fraction of input chunks below the grounding bar (distractors). */
  inputDistractorRatio: number
  retainedEvidenceRatio: number
  /**
   * Number of below-bar chunks that were RESCUED as linked second hops
   * by `reasoning_preserving` (rather than dropped as distractors).
   */
  secondHopRescues: number
  /**
   * Permanent alias for `secondHopRescues`. Both names will always be
   * present and equal — keeps parity with Python's
   * `report.second_hop_rescue_count` getter while preserving the
   * shorter `secondHopRescues` that 0.2.0 shipped.
   */
  secondHopRescueCount: number
  /**
   * Compared with a relevance-only baseline (DistractorFiltered),
   * how many MORE chunks did the chosen strategy retain? Positive
   * values mean rescued reasoning evidence beyond what a relevance
   * filter would have kept.
   */
  reasoningPreservationDelta: number
  /** Structural-expansion chunks added (neighbors / headings). */
  nExpanded: number
  /**
   * Chunks dropped because their grounding was below the distractor
   * bar (a subset of `removedTotal`).
   */
  distractorsPruned: number
  /**
   * Total chunks dropped during assembly (distractors + redundant +
   * over-budget).
   */
  removedTotal: number
  /**
   * Fraction of context tokens that are query-relevant (answer-bearing
   * density proxy).
   */
  evidenceDensity: number
  /** Fraction of selected chunks below the distractor grounding cutoff. */
  distractorRatio: number
  /**
   * Estimated tokens spent on chunks below the grounding bar (waste,
   * not evidence).
   */
  estimatedWasteTokens: number
  /**
   * `true` when nothing in the assembled context was above the grounding
   * floor — the query may share little vocabulary with the corpus.
   */
  lowConfidenceRetrieval: boolean
  /** The grounding ceiling that `low_confidence_retrieval` applied. */
  lowConfidenceThreshold: number
  /**
   * Audit trail of query rewrites applied (one entry per stage, in
   * chain order). Empty when no rewrite chain was used. See
   * `Document.contextWithRewrites`.
   */
  queryRewrites: Array<RewriteRecord>
  /** The human-readable Decision Report. */
  rendered: string
}
/**
 * One step in the rewrite chain — what the stage matched / added /
 * removed. Surfaced on `Report.queryRewrites` so the rewrite chain is
 * auditable.
 */
export interface RewriteRecord {
  /**
   * The `QueryRewrite::name` of the stage that emitted this record
   * (`"strip"` or `"vocabulary"` for the built-in implementations).
   */
  stage: string
  /** Input query handed to this stage. */
  fromQuery: string
  /** Output query produced by this stage. */
  toQuery: string
  /** Surface forms in the input that this stage matched. */
  matched: Array<string>
  /** Surface forms this stage *added* to the query (Vocabulary). */
  added: Array<string>
  /** Surface forms this stage *removed* from the query (Stripper). */
  removed: Array<string>
}
/** A file that `Document.fromFolder` skipped, with the reason why. */
export interface SkippedFile {
  /** Source path of the file that was skipped. */
  source: string
  /**
   * Human-readable reason: unsupported format, unreadable bytes, no
   * extractable text, etc.
   */
  reason: string
}
/**
 * Query grounding of a chunk's text: stopword-removed, Snowball-stemmed
 * query-term overlap, in `[0, 1]`. The same relevance signal the strategies
 * use internally; exposed so external code reuses redhop's exact notion of
 * relevance instead of drifting from it. Uses the English Snowball analyzer
 * — fixed here so the signal stays comparable across calls, independent of
 * any `Document`'s configured analyzer. (Since 0.3.2 the `Document` default
 * is a minimal raw pipeline; for analyzer-aware grounding go through
 * `Document.context().report`.)
 */
export declare function groundingScore(query: string, text: string): number
/**
 * Chunk↔chunk linkage strength: term-set Jaccard over the same normalized
 * terms — the bridge signal `reasoning_preserving` uses to decide whether
 * a low-relevance chunk is a rescuable second hop. In `[0, 1]`. Uses the
 * English Snowball analyzer (same fixed choice as `groundingScore`).
 */
export declare function linkStrength(a: string, b: string): number
/**
 * Diagnostic report over a representative sample of a workload's queries.
 *
 * Returned by `analyzeQuerySet`. Fields:
 * - `nQueries` — how many queries were analyzed
 * - `isTemplated` — `true` if share ≥ 0.50 AND ≥ 2 boilerplate terms
 * - `templateWordShare` — mean fraction of each query that's shared (0..1)
 * - `boilerplateTerms` — words in ≥ 80% of queries, sorted by frequency desc
 * - `estimatedDilutionCost` — `"high"` | `"medium"` | `"low"` | `"none"`
 * - `suggestedAction` — workload-shape recommendation
 */
export interface QuerySetReport {
  nQueries: number
  isTemplated: boolean
  templateWordShare: number
  boilerplateTerms: Array<string>
  estimatedDilutionCost: string
  suggestedAction: string
}
/**
 * Diagnostic output of [`Stripper.isEffectiveOn`].
 *
 * Every configured boilerplate term lands in exactly one of `removedTerms`
 * (fired on this query) or `unusedBoilerplate` (did not fire). The token
 * streams expose the analyzer's view so users can debug
 * "my Stripper compiled but seems to do nothing" without reading source.
 */
export interface StripperEffect {
  /** The query passed in, verbatim. */
  original: string
  /** What `apply(query)` would return. */
  stripped: string
  /** Analyzer tokens of the original query. */
  originalTokens: Array<string>
  /** Analyzer tokens of the stripped output. */
  strippedTokens: Array<string>
  /** Configured surface forms that fired on this query. */
  removedTerms: Array<string>
  /**
   * Configured surface forms that did NOT fire on this query. Includes
   * both "absent from input" and "present but mis-analyzed"; see
   * `probableSilentNoOp` for the actual-bug subset.
   */
  unusedBoilerplate: Array<string>
  /**
   * Subset of `unusedBoilerplate` where the term's lowercased raw
   * substring DOES appear in the query. These are the surprising
   * ones — terms the user expected to fire (the input contains them)
   * that nonetheless didn't strip. Usually a Snowball-stemming or
   * analyzer-token boundary mismatch. Empty list = no silent no-ops.
   */
  probableSilentNoOp: Array<string>
}
/**
 * Result of [`Vocabulary.enrich`] — the enriched chunk text plus the
 * per-chunk audit record. The record's `stage` is `"enrich"` (vs
 * `"vocabulary"` for the query-side `apply`).
 */
export interface EnrichResult {
  /** The chunk text with any matched vocabulary's synonyms appended. */
  text: string
  /**
   * The audit record for this enrichment: what was matched, what
   * surface forms were added, and the before/after text.
   */
  record: RewriteRecord
}
/**
 * Diagnostic over a representative sample of queries — detects
 * templated-workload dilution and reports which terms are doing it.
 *
 * Returns a [`QuerySetReport`]. Read `.isTemplated`, `.boilerplateTerms`,
 * `.suggestedAction`. See `docs/findings/QUERY_SET_ANALYZER.md` for the
 * cross-workload probe that validated the heuristic.
 *
 * ```js
 * const { analyzeQuerySet, Stripper } = require("redhop");
 * const r = analyzeQuerySet(myQueries);
 * if (r.isTemplated) {
 *   const stripper = new Stripper(r.boilerplateTerms);
 *   const ctx = doc.contextWithRewrites(query, [stripper]);
 * }
 * ```
 */
export declare function analyzeQuerySet(queries: Array<string>): QuerySetReport
/**
 * Optional inputs for [`evaluate`]. Any combination of fields is
 * supported — pass `answer` to unlock the lexical answer-quality
 * proxies (`faithfulnessLexical`, `relevancyLexical`); pass `goldChunks`
 * to unlock `contextRecall` / `contextPrecision`; pass `goldAnswer` to
 * unlock `answerTokenRecall`; pass `answer` AND `goldAnswer` to unlock
 * `correctnessLexical`. Omit all for self-eval only.
 */
export interface EvaluateOptions {
  /**
   * The LLM's answer text (what the model produced from the context).
   * Unlocks the lexical answer-quality proxies. Distinct from
   * `goldAnswer`, which is the ground truth.
   */
  answer?: string
  /** IDs of chunks that should appear in the assembled context. */
  goldChunks?: Array<string>
  /** Ground-truth answer text. */
  goldAnswer?: string
  /**
   * **Opt-in**: compute `faithfulness_judged` via two-pass claim
   * decomposition — extract atomic claims, verify them in a single
   * batched LLM call, return the mean score. More accurate than
   * the single-prompt default but costs +1 LLM call per evaluate.
   * Only meaningful when a `judge` is also supplied (via
   * `evaluateWithJudge`); ignored by the sync `evaluate(...)`.
   */
  decomposeFaithfulness?: boolean
  /**
   * **Opt-in**: compute `correctness_judged` via three-pass
   * classification — extract claims from the answer, extract from
   * the gold, classify each as TP / FP / FN, return F1. Also
   * populates the diagnostic counters `nCorrectnessTp`,
   * `nCorrectnessFp`, `nCorrectnessFn` on the report so callers
   * can debug which facts were missed vs hallucinated.
   */
  decomposeCorrectness?: boolean
}
/**
 * In-process evaluation report for one (query, BuiltContext) pair.
 *
 * Self-eval fields are always populated; gold-relative fields are
 * `null`/`undefined` unless the corresponding option was supplied. The
 * composite `overall` blends whichever fields are present.
 */
export interface EvalReport {
  /** `selected ∩ gold / |gold|`. `null` unless `goldChunks` was supplied. */
  contextRecall?: number
  /** `selected ∩ gold / |selected|`. `null` unless `goldChunks` was supplied. */
  contextPrecision?: number
  /**
   * Fraction of stemmed content terms in the gold answer that appear in
   * the assembled context. `null` unless `goldAnswer` was supplied.
   */
  answerTokenRecall?: number
  /**
   * Sentence-level token-overlap proxy for faithfulness: fraction of
   * the answer's sentences with at least half their content terms in
   * the assembled context. **Lexical proxy, NOT real faithfulness** —
   * an LLM judge is the right tool. `null` unless `answer` was supplied.
   */
  faithfulnessLexical?: number
  /**
   * Token-overlap between the query and the answer (Snowball-stemmed,
   * stopword-filtered). Proxy for "did the answer address the question".
   * `null` unless `answer` was supplied.
   */
  relevancyLexical?: number
  /**
   * Token-overlap between the LLM's answer and the gold answer. Proxy
   * for "did the LLM produce the right tokens". `null` unless BOTH
   * `answer` and `goldAnswer` were supplied.
   */
  correctnessLexical?: number
  /**
   * LLM-judged faithfulness. Populated by the async `evaluateWithJudge`
   * path; always `null` from the sync `evaluate` (JS callbacks can't
   * fire during a sync napi call). See `Judge.fromCallable(...)` for
   * how to wire a JS LLM client.
   */
  faithfulnessJudged?: number
  /**
   * LLM-judged relevancy. See `faithfulness_judged` for the sync vs
   * async note.
   */
  relevancyJudged?: number
  /**
   * LLM-judged correctness. See `faithfulness_judged` for the sync
   * vs async note.
   */
  correctnessJudged?: number
  /**
   * Number of atomic claims the judge extracted when
   * `decomposeFaithfulness: true` was passed and a judge was
   * supplied. `null` otherwise.
   */
  nFaithfulnessClaimsExtracted?: number
  /**
   * Number of those claims the judge scored ≥ 0.5 against the
   * context. `null` under the same conditions as
   * `nFaithfulnessClaimsExtracted`.
   */
  nFaithfulnessClaimsSupported?: number
  /**
   * Number of answer-claims supported by a reference claim.
   * Populated only when `decomposeCorrectness: true` was passed
   * and the classification pass succeeded.
   */
  nCorrectnessTp?: number
  /**
   * Number of answer-claims NOT supported by any reference claim.
   * Same population conditions as `nCorrectnessTp`.
   */
  nCorrectnessFp?: number
  /**
   * Number of reference-claims NOT covered by the answer. Same
   * population conditions as `nCorrectnessTp`.
   */
  nCorrectnessFn?: number
  /** Mean grounding over selected chunks, in `[0, 1]`. */
  meanGrounding: number
  /** Fraction of context tokens that are query-relevant. */
  evidenceDensity: number
  /** Fraction of input evidence that made it through assembly. */
  retainedEvidenceRatio: number
  /** Bridge passages saved by the reasoning-preserving rescue. */
  secondHopRescues: number
  /** `true` when every selected chunk is at-or-below the grounding ceiling. */
  lowConfidence: boolean
  /** Tokens spent on below-bar chunks. */
  estimatedWasteTokens: number
  /** Composite score in `[0, 1]` — the headline, blended. */
  overall: number
}
/**
 * Evaluate an assembled `BuiltContext` against optional ground truth.
 *
 * Self-eval (meanGrounding, evidenceDensity, secondHopRescues,
 * lowConfidence, …) is always populated. Pass `options.goldChunks` to
 * unlock `contextRecall` / `contextPrecision`; pass `options.goldAnswer`
 * to unlock `answerTokenRecall`. Both optional, any combination
 * supported.
 *
 * **What self-eval tells you, and what it doesn't.** Without gold, the
 * returned metrics describe how *focused* the context is on the query —
 * not whether the *correct* answer-bearing chunk is in there. A dense,
 * query-focused context can still be confidently wrong. For A/B
 * comparisons of `Stripper` / `Vocabulary` chains where you care about
 * correctness, supply `goldChunks` or `goldAnswer`; that's what unlocks
 * the retrieval-correctness signal.
 *
 * Zero LLM calls — every metric is computed from the same primitives the
 * runtime uses to make its Decision Report. See `EVALUATE_API.md` for
 * the "refraction not independent measurement" design choice.
 *
 * ```js
 * const ctx = doc.context("refund window");
 * const report = redhop.evaluate("refund window", ctx, {
 *   goldChunks: ["§3.4"],
 *   goldAnswer: "thirty days",
 * });
 * console.log(report.overall, report.contextRecall);
 * ```
 */
export declare function evaluate(query: string, context: BuiltContext, options?: EvaluateOptions | undefined | null): EvalReport
/**
 * Test-set aggregation. Pass an array of `EvalReport`s (typically one per
 * `(query, ctx, answer, gold)` triple in your test set) and get back means,
 * medians, and conditionally-present subset counts. Always-present metrics
 * are means/medians over all reports; optional metrics (gold-relative
 * scores, judged scores) are means over only the subset where they were
 * populated, with an `nWith…` companion so callers can spot "this number is
 * computed from 3 of 200 reports" before reading too much into it.
 *
 * Mirrors `redhop.summarize(reports)` in Python and `redhop::summarize(&[...])`
 * in Rust.
 */
export declare function summarize(reports: Array<EvalReport>): EvalSummary
/**
 * Aggregate stats for a test set. Returned by `summarize(reports)`.
 * Always-present metrics are means/medians over all `n` reports;
 * conditionally-present metrics (gold-relative + LLM-judged) are means
 * over only the subset where each was populated. `nWith…` reports the
 * subset size so a caller can spot a number computed from 3 of 200
 * reports before reading too much into it.
 */
export interface EvalSummary {
  /** Total number of reports in the input. */
  n: number
  /** Mean of `overall` across all reports. */
  meanOverall: number
  /** Median of `overall` across all reports. */
  medianOverall: number
  /** Mean of `meanGrounding` across all reports. */
  meanGrounding: number
  /** Mean of `evidenceDensity` across all reports. */
  meanEvidenceDensity: number
  /** Fraction of reports where `lowConfidence` was true, in `[0, 1]`. */
  lowConfidenceRate: number
  meanContextRecall?: number
  /** Number of reports where `contextRecall` was populated. */
  nWithContextRecall: number
  meanContextPrecision?: number
  nWithContextPrecision: number
  meanAnswerTokenRecall?: number
  nWithAnswerTokenRecall: number
  meanFaithfulnessLexical?: number
  nWithFaithfulnessLexical: number
  meanRelevancyLexical?: number
  nWithRelevancyLexical: number
  meanCorrectnessLexical?: number
  nWithCorrectnessLexical: number
  meanFaithfulnessJudged?: number
  nWithFaithfulnessJudged: number
  meanRelevancyJudged?: number
  nWithRelevancyJudged: number
  meanCorrectnessJudged?: number
  nWithCorrectnessJudged: number
}
/**
 * Options for [`evaluate_with_judge`] — same as `EvaluateOptions` plus
 * a `judge` field. Distinct type because napi-rs doesn't allow object-
 * type options with class-typed fields directly; we accept the Judge
 * via the function-level signature instead and split the options into
 * the existing struct (free of class types) + a separate Judge arg.
 */
export declare function evaluateWithJudge(query: string, context: BuiltContext, judge: Judge, options?: EvaluateOptions | undefined | null): Promise<EvalReport>
/**
 * One qualitative dimension to score the answer on. `highIsGood`
 * controls polarity — when `false` (e.g. harmfulness), the LLM's
 * raw score is INVERTED to `1 - raw` before being returned, so high
 * values still mean "good answer" across the report.
 */
export interface Aspect {
  /** Short label, used as the key in the returned `CritiqueReport`. */
  name: string
  /** What to score, phrased as a question the LLM can answer 0–1. */
  definition: string
  /**
   * `true` keeps the LLM's raw score; `false` inverts it (so high
   * = good regardless of aspect polarity). Default `true`.
   */
  highIsGood?: boolean
}
/**
 * One scored aspect — the same shape as a tuple, but napi-rs only
 * serializes plain objects so we name it.
 */
export interface AspectScore {
  /** Aspect's `name`. */
  name: string
  /**
   * Polarity-corrected score in `[0, 1]`, or `null` if the judge
   * errored on this aspect.
   */
  score?: number
}
/**
 * Result of [`critique`]. The `scores` array preserves input order;
 * `null` scores are aspects where the judge call errored.
 */
export interface CritiqueReport {
  /** Number of aspects scored. */
  n: number
  /**
   * Per-aspect scores in input order. Iterate the array, or look
   * up by name on the JS side: `report.scores.find(s => s.name === "x")?.score`.
   */
  scores: Array<AspectScore>
}
/**
 * Optional inputs for [`critique`] beyond the required `answer`,
 * `aspects`, and `judge` args.
 */
export interface CritiqueOptions {
  /**
   * Context to embed in each aspect's prompt — useful for aspects
   * that need the source material to score.
   */
  context?: string
  /**
   * Query to embed in each aspect's prompt — useful for aspects
   * like "does the answer address the question".
   */
  query?: string
}
export declare function critique(answer: string, aspects: Array<Aspect>, judge: Judge, options?: CritiqueOptions | undefined | null): Promise<CritiqueReport>
/**
 * Optional fields for the [`Chunk`] constructor's options bag.
 *
 * `metadata` is an open object (JSON-compatible values). Known keys are
 * picked up by the citations machinery — currently `page` (int),
 * `heading` (string), `line` (int). Anything else is preserved but
 * not surfaced by the built-in citations contract.
 */
export interface ChunkOptions {
  /**
   * The chunk's stable identifier. Defaults to `c0`, `c1`, …
   * based on position in the array passed to `Document.fromChunks`.
   */
  id?: string
  /**
   * The chunk's provenance: file path, URL, logical handle. Defaults
   * to `"input"`. This is what `ctx.citations[*].source` displays.
   */
  source?: string
  /**
   * Open metadata object (JSON-compatible values). Known keys
   * (`page`, `heading`, `line`) are picked up by citations.
   */
  metadata?: Record<string, any>
  /** Token count (defaults to whitespace word count). */
  tokenCount?: number
  /** Optional precomputed dense vector for embedding-based scoring. */
  embedding?: Array<number>
}
/**
 * Optional knobs for the low-level context functions. Every field is
 * optional; defaults match RedHop's `ContextConfig::default()`.
 */
export interface ContextOptions {
  /**
   * Assembly strategy: `auto` (default for `Document`) / `reasoning_preserving`
   * (default for the low-level path) / `distractor_filtered` / `redundancy_pruned`
   * / `max_density` / `raw_topk`.
   */
  strategy?: string
  /** Token budget cap on the assembled context. Default 8192. */
  tokenBudget?: number
  /**
   * Grounding bar below which a chunk is treated as a distractor.
   * Default 0.10.
   */
  distractorMinGrounding?: number
  /** Jaccard floor for chunk↔chunk linkage. Default 0.12. */
  linkMinJaccard?: number
  /**
   * Token-count gate for the Auto strategy's passthrough decision.
   * Default 1500.
   */
  autoPassthroughMaxTokens?: number
  /** Cosine ceiling above which a chunk is treated as redundant. Default 0.92. */
  redundancyMaxCosine?: number
  /**
   * Preserve source-document order of selected chunks instead of the
   * strategy's relevance order. Useful for chat histories / transcripts
   * where chronology matters. Default `false` (existing relevance-first
   * behavior). See `docs/findings/CHAT_RAG.md` (TODO) and
   * `crates/examples/examples/chat_rag.rs` for the worked pattern.
   */
  preserveOrder?: boolean
}
/**
 * Assemble the reasoning context from caller-supplied retrieved chunks
 * (skip RedHop's chunking + retrieval and use it only for the final
 * allocation step). Returns the same `BuiltContext` shape as
 * `Document.context()`.
 */
export declare function buildContext(query: string, retrievedChunks: Array<Chunk>, options?: ContextOptions | undefined | null): BuiltContext
/**
 * Distractor-only filter (no budget truncation): keep everything above the
 * grounding bar, drop only the off-topic chunks. Returns a `BuiltContext`
 * whose `text` / `chunks` / `citations` reflect the filtered set.
 */
export declare function filterContext(query: string, retrievedChunks: Array<Chunk>, options?: ContextOptions | undefined | null): BuiltContext
/**
 * Pure diagnostics over caller-supplied chunks: what would RedHop do, and
 * why, without paying the assembly cost. Returns the same `Report` shape
 * as `Document.context().report`.
 *
 * Like Python's `redhop.analyze_context`, this is a "no-budget" surface —
 * the `token_budget` option, if supplied, is ignored so the report's
 * `budget_utilization` reflects pure-analysis semantics (all chunks
 * counted) and stays consistent across bindings.
 */
export declare function analyzeContext(query: string, retrievedChunks: Array<Chunk>, options?: ContextOptions | undefined | null): Report
/**
 * Token economics over caller-supplied chunks (evidence density, distractor
 * ratio, redundancy, estimated wasted tokens). Returns a JSON string —
 * callers `JSON.parse()` for the typed shape.
 *
 * Like Python's `redhop.context_economics`, this is a "no-budget" surface
 * — the `token_budget` option is ignored so `budget_utilization` is
 * computed against an unbounded budget (essentially 0), matching the
 * "pure analysis, no filtering, no truncation" intent.
 */
export declare function contextEconomics(query: string, retrievedChunks: Array<Chunk>, options?: ContextOptions | undefined | null): string
/**
 * The assembled context: prompt string, selected chunks, citations, report.
 *
 * Class (not plain object) so it can hold the underlying Rust `BuiltContext`
 * for in-process operations like [`evaluate`]. All four existing fields
 * (`text`, `chunks`, `citations`, `report`) remain accessible as JS
 * properties via getters.
 */
export declare class BuiltContext {
  /** The assembled context as a single prompt string (drop-in for `llm.generate`). */
  get text(): string
  /** Selected chunks in presentation order, as plain strings. */
  get chunks(): Array<string>
  /** Per-chunk provenance — source, page, heading, line, text. */
  get citations(): Array<Citation>
  /** The Decision Report: what was kept, what was dropped, why. */
  get report(): Report
}
/**
 * A document you reason over. RedHop owns chunking, internal retrieval, and
 * reasoning-preserving context allocation; you think in documents and queries.
 */
export declare class Document {
  /** Build from raw text you already have. */
  static fromText(text: string, options?: Options | undefined | null): Document
  /**
   * Build from typed `Chunk` instances you already produced.
   * Bypasses the chunker — the caller's chunks are preserved 1-to-1
   * (no resplitting) with their `source` / `id` / `metadata` all
   * surviving into the index.
   */
  static fromChunks(chunks: Array<Chunk>, options?: Options | undefined | null): Document
  /** Build straight from a file on disk — PDF, DOCX, PPTX, XLSX, or text/code. */
  static fromFile(path: string, options?: Options | undefined | null): Document
  /**
   * Build from in-memory bytes you fetched (S3 / GCS / Azure Blob / HTTP / DB).
   * `source` (e.g. `"contract.pdf"`) picks the parser and is the citation source.
   */
  static fromBytes(data: Buffer, source: string, options?: Options | undefined | null): Document
  /**
   * Build one index from every readable file in a folder. Honors `.gitignore` +
   * `ignore` globs; `persist: true` saves an incremental on-disk index.
   */
  static fromFolder(path: string, options?: FolderOptions | undefined | null): Document
  /** Number of chunks the document holds. */
  get chunkCount(): number
  /**
   * Number of source files indexed into this Document. `1` for the
   * single-source constructors (`fromText`, `fromFile`, `fromBytes`,
   * `fromChunks`); the readable file count for `fromFolder` (excludes
   * `skippedFiles`).
   */
  get nFiles(): number
  /**
   * Files that `fromFolder` skipped, as `{ source, reason }` objects —
   * unsupported formats, unreadable bytes, no extractable text (e.g.
   * scanned PDFs without OCR), etc. Empty array for single-source
   * constructors.
   */
  get skippedFiles(): Array<SkippedFile>
  /**
   * Assemble the reasoning context for a query (retrieve → allocate).
   * `neighbors` / `includeHeading` add structural context expansion.
   */
  context(query: string, budget?: number | undefined | null, neighbors?: number | undefined | null, includeHeading?: boolean | undefined | null): BuiltContext
  /**
   * Run a query through a chain of `Stripper` / `Vocabulary` rewrites
   * before retrieval, then assemble context as `.context(...)` does.
   *
   * `rewrites` is an ordered array — each stage sees the previous
   * stage's output. The per-stage audit trail lands on
   * `ctx.report.queryRewrites` as an array of `RewriteRecord`.
   *
   * Mirrors `redhop::Document::context_with_rewrites` in the Rust core.
   */
  contextWithRewrites(query: string, rewrites: Array<Stripper | Vocabulary>): BuiltContext
  /**
   * Pure diagnostics: retrieve + score for the query but DON'T assemble
   * the prompt. Returns the same `Report` shape as `context().report` so
   * callers can audit what would happen without paying assembly cost or
   * stringifying the chunks.
   */
  analyze(query: string): Report
}
/**
 * Compiled boilerplate-removal rewrite. Token-level matching using the
 * document's analyzer, so a single-token stripper key cannot accidentally
 * erase a substring inside a longer word (an `"of"` stripper does **not**
 * erase the `"of"` inside `"office"`).
 *
 * ```js
 * const stripper = new redhop.Stripper([
 *   "highlight", "the", "parts", "of", "this",
 *   "contract", "related", "to",
 * ]);
 * ```
 *
 * Pass into the rewrite chain on `Document.contextWithRewrites(...)`.
 */
export declare class Stripper {
  constructor(boilerplate: Array<string>)
  /**
   * Apply the stripper to a query string outside the rewrite chain
   * (ad-hoc / pipeline-outside cases). Returns the rewritten string;
   * the audit record is discarded — use the chain via
   * `Document.contextWithRewrites(...)` if you want the trail in the
   * Decision Report.
   */
  apply(query: string): string
  /**
   * Diagnose how this Stripper would act on `query`. Returns an object
   * with the analyzer's view of the input and the configured boilerplate
   * terms that did / did not fire / are silent no-ops.
   *
   * Read `probableSilentNoOp` first: a non-empty list means you
   * configured a term, the raw query contains it, but the analyzer
   * stemmed/normalized it away from the query's tokens (the actual
   * bug). Empty list means every configured term that should have
   * fired, did. The long-tail `unusedBoilerplate` is informational
   * (terms genuinely absent from this input).
   *
   * ```js
   * const s = new redhop.Stripper(["highlight", "the", "of", "antidisestablishmentarianism"]);
   * const effect = s.isEffectiveOn("highlight the parts of office hours");
   * console.log(effect.removedTerms);           // [ 'highlight', 'the', 'of' ]
   * console.log(effect.unusedBoilerplate);      // [ 'antidisestablishmentarianism' ]
   * console.log(effect.probableSilentNoOp);     // [] — every present term fired
   * console.log(effect.stripped);               // 'parts office hours'
   * ```
   */
  isEffectiveOn(query: string): StripperEffect
  /** Number of distinct boilerplate surface forms compiled. */
  get length(): number
}
/**
 * Compiled workload-curated equivalence classes (term → synonyms). Each
 * entry's key, when found in the query at token granularity, triggers
 * appending its synonyms to the rewritten query. With
 * `Vocabulary.bidirectional({...})`, any class member can be the trigger
 * and the others get appended (so PTO ↔ "paid time off" works in both
 * directions).
 *
 * ```js
 * const vocab = new redhop.Vocabulary({
 *   "change of control": ["merger", "successor", "acquisition"],
 *   "non-compete":       ["restraint", "non-competition"],
 * });
 * // symmetric:
 * const pto = redhop.Vocabulary.bidirectional({
 *   pto: ["paid time off", "vacation"],
 * });
 * ```
 */
export declare class Vocabulary {
  /**
   * Asymmetric vocabulary: the first form of each entry is the only
   * trigger; the rest are appended on match.
   */
  constructor(entries: Record<string, Array<string>>)
  /**
   * Symmetric (bidirectional) vocabulary: any class member can trigger
   * expansion; the other members get appended.
   */
  static bidirectional(entries: Record<string, Array<string>>): Vocabulary
  /**
   * Apply the vocabulary to a query string outside the rewrite chain.
   * Returns the rewritten string; the audit record is discarded — use
   * the chain via `Document.contextWithRewrites(...)` if you want the
   * trail in the Decision Report.
   */
  apply(query: string): string
  /**
   * Chunk-side enrichment — the symmetric to `apply`. Same compiled
   * vocabulary, applied at ingest time to a chunk's text so opaque
   * coded units (column names, error codes, API symbols, defined
   * terms) become matchable for natural-language queries that don't
   * share surface forms with them.
   *
   * Returns `{ text, record }` so the caller can collect the per-chunk
   * audit trail. Use pattern:
   *
   * ```js
   * const vocab = new redhop.Vocabulary({
   *   usrSvc:  ["user service", "signup", "account creation"],
   *   calcAmt: ["calculate amount", "billing total"],
   * });
   * const enrichedChunks = [];
   * for (const chunk of rawChunks) {
   *   const { text, record } = vocab.enrich(chunk);
   *   enrichedChunks.push(text);
   *   // if (record.matched.length) audit.push(record);
   * }
   * const doc = redhop.Document.fromChunks(enrichedChunks);
   * ```
   *
   * **When this earns its keep.** `value ∝ shortness × opacity ×
   * dictionary-exists`. Schema columns, API symbols, error codes,
   * defined contract terms, clinical abbreviations — all extreme
   * cases. Long descriptive prose is redundant. Bolting the same
   * boilerplate onto every chunk re-creates the low-IDF dilution
   * from CUAD_PRF_NULL. See `docs/findings/VOCABULARY_ENRICH.md`.
   */
  enrich(chunk: string): EnrichResult
  /** Number of equivalence classes compiled. */
  get length(): number
}
/**
 * judged Judge: wraps a JS callable that scores a (prompt, system)
 * pair on `[0, 1]`. Construct via `Judge.fromCallable(fn, name?)` and
 * pass to `evaluateWithJudge(query, ctx, judge, opts)`. Call
 * `.cached()` to memoize identical prompts across calls — useful for
 * CI determinism and avoiding double-billing on re-runs.
 *
 * **Callback signature.** The JS callable receives THREE positional
 * args: `(err, prompt, system)`. The first arg is napi-rs's error
 * channel (null on the normal path; non-null only if the napi layer
 * itself failed to deserialize the input — vanishingly rare for
 * plain strings). Most users pass it through with destructuring:
 *
 * ```js
 * const judge = redhop.Judge.fromCallable(async (err, prompt, system) => {
 *   if (err) throw err;
 *   const resp = await openai.chat.completions.create({ ... });
 *   return parseFloat(resp.choices[0].message.content.trim());
 * }, "gpt-4o-mini").cached();
 *
 * const report = await redhop.evaluateWithJudge(
 *   query, ctx, judge,
 *   { answer: "Thirty days from purchase.", goldAnswer: "thirty days" },
 * );
 * ```
 *
 * **Return type.** The callable may return either a `number` (the
 * score) or a `string` (the raw LLM text — needed for the Phase-6
 * claim-extraction call when `decomposeFaithfulness: true`). A
 * numeric string ("0.8", "80%") is parsed via the same `parse_score`
 * the Rust core uses; a non-numeric string keeps score=0 but
 * preserves raw_text for downstream parsing.
 *
 * **Error isolation.** A JS-thrown exception in the callable surfaces
 * as `Err` on the underlying future. `redhop::evaluate` treats that
 * as "this metric is unavailable" and leaves the corresponding
 * `_judged` field as `null` — the process doesn't crash and the
 * lexical fields stay populated.
 */
export declare class Judge {
  /**
   * Wrap a JS callable as a Judge. The callable is invoked as
   * `callable(prompt, system) -> number | Promise<number>`. The
   * returned value is normalized to `[0, 1]` via the same parser
   * the Rust core uses (`judge::parse_score` accepts floats,
   * percentages, "yes"/"no").
   *
   * `name` namespaces the cache key — swap it when you swap models
   * so cached `gpt-4o-mini` scores don't reappear under
   * `claude-haiku`.
   */
  static fromCallable(callable: (err: Error | null, arg0: string, arg1?: string | undefined | null) => any, name?: string | undefined | null): Judge
  /**
   * Return a NEW Judge wrapping this one with an in-memory cache.
   * Identical `(prompt, system)` pairs hit the cache instead of
   * re-calling the JS callable.
   */
  cached(): Judge
  /** Stable identifier used in the cache key. */
  get name(): string
}
/**
 * One unit of content in a [`Document`] — the construction primitive
 * for callers who pre-chunked their corpus elsewhere (schema rows,
 * API endpoints, code symbols, defined contract terms, pre-segmented
 * paragraphs).
 *
 * Two concepts are kept distinct:
 * - **`source`** — *provenance*: where the chunk came from.
 * - **`id`** — *identity*: a stable identifier for dedup and gold-chunk
 *   evaluation.
 *
 * ```js
 * const chunks = [
 *   new redhop.Chunk(
 *     "orders.amt (decimal) — order amount / revenue / spend in USD",
 *     { source: "schema.sql", id: "orders.amt",
 *       metadata: { table: "orders", column: "amt", type: "decimal" } },
 *   ),
 *   new redhop.Chunk(
 *     "9.1 Governing Law. This Agreement shall be governed by …",
 *     { source: "contract.pdf", metadata: { page: 12, heading: "9.1 Governing Law" } },
 *   ),
 * ];
 * const doc = redhop.Document.fromChunks(chunks);
 * ```
 */
export declare class Chunk {
  /** Construct a chunk from text plus optional fields. */
  constructor(text: string, options?: ChunkOptions | undefined | null)
  get text(): string
  get source(): string | null
  get id(): string | null
  get tokenCount(): number | null
  get metadata(): Record<string, any>
}
