/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Chunking / assembly / retrieval options for the `Document.from*` constructors.
 * Every field is optional; omit for evidence-backed defaults.
 */
export interface Options {
  /** Source label for `fromText` (default `"document"`). */
  source?: string
  /** Target tokens per chunk (index-time). Default 128. */
  chunkSize?: number
  /** Sentences of overlap between adjacent chunks. Default 1. */
  chunkOverlap?: number
  /** Default assembly token budget (override per call). Default 8192. */
  tokenBudget?: number
  /** Candidates to retrieve before assembly. Default 20. */
  candidateK?: number
  /**
   * Assembly strategy: `auto` (default) · `reasoning_preserving` ·
   * `distractor_filtered` · `redundancy_pruned` · `max_density` · `raw_topk`.
   */
  strategy?: string
  /** `"lexical"` (default, BM25), `"hybrid"`, or `"semantic"`. */
  retrieval?: string
  /** Built-in embedding model to download (`"bge-small"` / `"bge-base"`). */
  model?: string
  /** Advanced: path to a local ONNX embedding model. */
  embedderModel?: string
  /** Advanced: path to its tokenizer. */
  embedderTokenizer?: string
  /** Advanced: the model's output dimension. Default 384. */
  embedderDim?: number
  /** Advanced: `"cls"` (default) or `"mean"`. */
  embedderPooling?: string
  /** Advanced: query prefix for asymmetric models (E5: `"query: "`). */
  embedderQueryPrefix?: string
  /** Advanced: passage prefix for asymmetric models (E5: `"passage: "`). */
  embedderPassagePrefix?: string
  /** Hybrid BM25 prune depth. Default 50. */
  candidatePool?: number
  /**
   * Optional second-stage cross-encoder reranker by name (`"cross-encoder"`,
   * auto-downloaded). Reorders the candidate pool by jointly scoring each
   * `(query, passage)` pair. Works under any retrieval tier.
   */
  rerank?: string
  /**
   * Floor on the number of candidates delivered to the assembler. Under
   * `"hybrid"` / `"semantic"` retrieval, if the primary tier returns
   * fewer, a BM25 fallback tops the result up to this number. Default
   * `0` (off). No effect under `"lexical"`. Pair with
   * `report.lowConfidenceRetrieval` to detect a weak-fallback case.
   */
  minCandidates?: number
  /**
   * Lexical analyzer language. Drives both BM25 retrieval and the
   * grounding scorer's term extraction so the two layers agree on what
   * counts as "the same term" (English `compression` finds `compress`,
   * German `Bücher` finds `Buch`, etc.). Default `"english"`.
   *
   * Supported: `"arabic"`, `"danish"`, `"dutch"`, `"english"`,
   * `"finnish"`, `"french"`, `"german"`, `"greek"`, `"hungarian"`,
   * `"italian"`, `"norwegian"`, `"portuguese"`, `"romanian"`,
   * `"russian"`, `"spanish"`, `"swedish"`, `"tamil"`, `"turkish"` —
   * the 18 Snowball Porter2 languages. Unknown strings ERROR (no
   * silent fallback to English; a typo'd `"germann"` surfaces).
   */
  language?: string
}
/** Extra options for `Document.fromFolder` (plus the chunking/retrieval `options`). */
export interface FolderOptions {
  /** Recurse into subdirectories. Default true. */
  recursive?: boolean
  /** Honor `.gitignore`. Default true. */
  gitignore?: boolean
  /** Extra gitignore-style globs to exclude, e.g. `["*.lock", "tests/**"]`. */
  ignore?: Array<string>
  /** Persist the index to disk and reload it incrementally on the next run. */
  persist?: boolean
  /** Where the persisted index lives (default `<folder>/.redhop`). */
  indexDir?: string
  /** Chunking / retrieval options (same fields as the other constructors). */
  options?: Options
}
/** Where one selected chunk came from — for citing the evidence. */
export interface Citation {
  source: string
  page?: number
  heading?: string
  line?: number
  text: string
}
/** The Decision Report: what the assembly did, and why. */
export interface Report {
  /**
   * The strategy actually used — the resolved concrete strategy after
   * `auto` (if requested) was decided. One of `"raw_topk"`,
   * `"distractor_filtered"`, `"redundancy_pruned"`, `"max_density"`,
   * `"reasoning_preserving"`. Never `"auto"` (Auto is always resolved
   * before assembly).
   */
  strategy: string
  /**
   * What the caller requested — may be `"auto"`. Differs from `strategy`
   * when the Auto policy resolved to a concrete action.
   */
  requestedStrategy: string
  /** `"passthrough"` | `"prune"` | `"not_auto"`. */
  autoDecision: string
  /** Total tokens in the input (retrieved) set, before assembly. */
  inputTokens: number
  /** The token-budget cap applied during assembly. */
  tokenBudget: number
  totalTokens: number
  /** `total_tokens / token_budget` — how much of the budget was used. */
  tokenUtilization: number
  /** How many chunks were in the input (retrieved) set. */
  nInputChunks: number
  /** How many chunks survived assembly into the final context. */
  nSelected: number
  /** Fraction of input chunks below the grounding bar (distractors). */
  inputDistractorRatio: number
  retainedEvidenceRatio: number
  /**
   * Number of below-bar chunks that were RESCUED as linked second hops
   * by `reasoning_preserving` (rather than dropped as distractors).
   */
  secondHopRescues: number
  /**
   * Permanent alias for `secondHopRescues`. Both names will always be
   * present and equal — keeps parity with Python's
   * `report.second_hop_rescue_count` getter while preserving the
   * shorter `secondHopRescues` that 0.2.0 shipped.
   */
  secondHopRescueCount: number
  /**
   * Compared with a relevance-only baseline (DistractorFiltered),
   * how many MORE chunks did the chosen strategy retain? Positive
   * values mean rescued reasoning evidence beyond what a relevance
   * filter would have kept.
   */
  reasoningPreservationDelta: number
  /** Structural-expansion chunks added (neighbors / headings). */
  nExpanded: number
  /**
   * Chunks dropped because their grounding was below the distractor
   * bar (a subset of `removedTotal`).
   */
  distractorsPruned: number
  /**
   * Total chunks dropped during assembly (distractors + redundant +
   * over-budget).
   */
  removedTotal: number
  /**
   * Fraction of context tokens that are query-relevant (answer-bearing
   * density proxy).
   */
  evidenceDensity: number
  /** Fraction of selected chunks below the distractor grounding cutoff. */
  distractorRatio: number
  /**
   * Estimated tokens spent on chunks below the grounding bar (waste,
   * not evidence).
   */
  estimatedWasteTokens: number
  /**
   * `true` when nothing in the assembled context was above the grounding
   * floor — the query may share little vocabulary with the corpus.
   */
  lowConfidenceRetrieval: boolean
  /** The grounding ceiling that `low_confidence_retrieval` applied. */
  lowConfidenceThreshold: number
  /** The human-readable Decision Report. */
  rendered: string
}
/** A file that `Document.fromFolder` skipped, with the reason why. */
export interface SkippedFile {
  /** Source path of the file that was skipped. */
  source: string
  /**
   * Human-readable reason: unsupported format, unreadable bytes, no
   * extractable text, etc.
   */
  reason: string
}
/**
 * Query grounding of a chunk's text: stopword-removed, Snowball-stemmed
 * query-term overlap, in `[0, 1]`. The same relevance signal the strategies
 * use internally; exposed so external code reuses redhop's exact notion of
 * relevance instead of drifting from it. Uses the default English analyzer;
 * non-English content should reach grounding via `Document.context().report`
 * (which carries the configured analyzer end-to-end).
 */
export declare function groundingScore(query: string, text: string): number
/**
 * Chunk↔chunk linkage strength: term-set Jaccard over the same normalized
 * terms — the bridge signal `reasoning_preserving` uses to decide whether
 * a low-relevance chunk is a rescuable second hop. In `[0, 1]`. Uses the
 * default English analyzer.
 */
export declare function linkStrength(a: string, b: string): number
/**
 * Diagnostic report over a representative sample of a workload's queries.
 *
 * Returned by `analyzeQuerySet`. Fields:
 * - `nQueries` — how many queries were analyzed
 * - `isTemplated` — `true` if share ≥ 0.50 AND ≥ 2 boilerplate terms
 * - `templateWordShare` — mean fraction of each query that's shared (0..1)
 * - `boilerplateTerms` — words in ≥ 80% of queries, sorted by frequency desc
 * - `estimatedDilutionCost` — `"high"` | `"medium"` | `"low"` | `"none"`
 * - `suggestedAction` — workload-shape recommendation
 */
export interface QuerySetReport {
  nQueries: number
  isTemplated: boolean
  templateWordShare: number
  boilerplateTerms: Array<string>
  estimatedDilutionCost: string
  suggestedAction: string
}
/**
 * Drop boilerplate tokens from a query before retrieval.
 *
 * Token matching is case-insensitive on alphanumeric tokens; surviving
 * tokens are rejoined with single spaces, with punctuation preserved.
 * Mechanism: docs/findings/CUAD_RECALL_GAP.md.
 *
 * ```js
 * const { dropTemplateTerms } = require("redhop");
 * const stripped = dropTemplateTerms(
 *   'Highlight the parts related to "Change of Control".',
 *   ["highlight", "the", "parts", "related", "to"],
 * );
 * // stripped === '"Change of Control".'
 * ```
 */
export declare function dropTemplateTerms(query: string, boilerplate: Array<string>): string
/**
 * Append high-IDF discriminative terms to a query when a known key appears.
 *
 * The additive counterpart to `dropTemplateTerms`. Pass an object mapping
 * each known key (clause name, error code, policy slug — anything
 * workload-specific) to an array of synonyms. For every key whose
 * case-insensitive substring appears in the query, the synonyms are
 * appended with a single space separator. Matches against the *original*
 * query only — no recursive chaining, no duplicates.
 *
 * ```js
 * const { expandQueryTerms } = require("redhop");
 * const expansions = {
 *   "change of control": ["merger", "successor", "acquisition"],
 *   "non-compete":       ["restraint", "non-competition"],
 * };
 * const expanded = expandQueryTerms(
 *   "What about Change of Control clauses?",
 *   expansions,
 * );
 * // → "What about Change of Control clauses? merger successor acquisition"
 * ```
 *
 * Same workload-specific discipline as `dropTemplateTerms`: the library
 * ships the mechanism, the caller supplies the dict. See
 * `docs/findings/CUAD_CLAUSE_EXPANSION.md` for the worked CUAD example.
 */
export declare function expandQueryTerms(query: string, expansions: Record<string, Array<string>>): string
/**
 * Diagnostic over a representative sample of queries — detects
 * templated-workload dilution and reports which terms are doing it.
 *
 * Returns a [`QuerySetReport`]. Read `.isTemplated`, `.boilerplateTerms`,
 * `.suggestedAction`. See `docs/findings/QUERY_SET_ANALYZER.md` for the
 * cross-workload probe that validated the heuristic.
 *
 * ```js
 * const { analyzeQuerySet, dropTemplateTerms } = require("redhop");
 * const r = analyzeQuerySet(myQueries);
 * if (r.isTemplated) {
 *   const stripped = dropTemplateTerms(query, r.boilerplateTerms);
 *   const ctx = doc.context(stripped, { strategy: "raw_topk" });
 * }
 * ```
 */
export declare function analyzeQuerySet(queries: Array<string>): QuerySetReport
/**
 * Optional gold signals for [`evaluate`]. Any combination of fields is
 * supported — pass `goldChunks` to unlock `contextRecall` /
 * `contextPrecision`; pass `goldAnswer` to unlock `answerTokenRecall`;
 * pass both for all three. Omit both for self-eval only.
 */
export interface EvaluateOptions {
  /** IDs of chunks that should appear in the assembled context. */
  goldChunks?: Array<string>
  /** Ground-truth answer text. */
  goldAnswer?: string
}
/**
 * In-process evaluation report for one (query, BuiltContext) pair.
 *
 * Self-eval fields are always populated; gold-relative fields are
 * `null`/`undefined` unless the corresponding option was supplied. The
 * composite `overall` blends whichever fields are present.
 */
export interface EvalReport {
  /** `selected ∩ gold / |gold|`. `null` unless `goldChunks` was supplied. */
  contextRecall?: number
  /** `selected ∩ gold / |selected|`. `null` unless `goldChunks` was supplied. */
  contextPrecision?: number
  /**
   * Fraction of stemmed content terms in the gold answer that appear in
   * the assembled context. `null` unless `goldAnswer` was supplied.
   */
  answerTokenRecall?: number
  /** Mean grounding over selected chunks, in `[0, 1]`. */
  meanGrounding: number
  /** Fraction of context tokens that are query-relevant. */
  evidenceDensity: number
  /** Fraction of input evidence that made it through assembly. */
  retainedEvidenceRatio: number
  /** Bridge passages saved by the reasoning-preserving rescue. */
  secondHopRescues: number
  /** `true` when every selected chunk is at-or-below the grounding ceiling. */
  lowConfidence: boolean
  /** Tokens spent on below-bar chunks. */
  estimatedWasteTokens: number
  /** Composite score in `[0, 1]` — the headline, blended. */
  overall: number
}
/**
 * Evaluate an assembled `BuiltContext` against optional ground truth.
 *
 * Self-eval (meanGrounding, evidenceDensity, secondHopRescues,
 * lowConfidence, …) is always populated. Pass `options.goldChunks` to
 * unlock `contextRecall` / `contextPrecision`; pass `options.goldAnswer`
 * to unlock `answerTokenRecall`. Both optional, any combination
 * supported.
 *
 * Zero LLM calls — every metric is computed from the same primitives the
 * runtime uses to make its Decision Report. See `EVALUATE_API.md` for
 * the "refraction not independent measurement" design choice.
 *
 * ```js
 * const ctx = doc.context("refund window");
 * const report = redhop.evaluate("refund window", ctx, {
 *   goldChunks: ["§3.4"],
 *   goldAnswer: "thirty days",
 * });
 * console.log(report.overall, report.contextRecall);
 * ```
 */
export declare function evaluate(query: string, context: BuiltContext, options?: EvaluateOptions | undefined | null): EvalReport
/**
 * A single retrieved chunk for the low-level `buildContext` / `filterContext`
 * / `analyzeContext` / `contextEconomics` functions.
 */
export interface ChunkInput {
  /** The chunk text. Required. */
  text: string
  /** Stable identifier. Defaults to `c<index>`. */
  id?: string
  /** Source path / label. Defaults to `"input"`. */
  source?: string
  /** Token count (defaults to whitespace word count). */
  tokenCount?: number
  /** Optional dense vector (for embedding-based scoring downstream). */
  embedding?: Array<number>
  /** Retrieval score from the upstream retriever. Defaults to `1.0`. */
  score?: number
}
/**
 * Optional knobs for the low-level context functions. Every field is
 * optional; defaults match RedHop's `ContextConfig::default()`.
 */
export interface ContextOptions {
  /**
   * Assembly strategy: `auto` (default for `Document`) / `reasoning_preserving`
   * (default for the low-level path) / `distractor_filtered` / `redundancy_pruned`
   * / `max_density` / `raw_topk`.
   */
  strategy?: string
  /** Token budget cap on the assembled context. Default 8192. */
  tokenBudget?: number
  /**
   * Grounding bar below which a chunk is treated as a distractor.
   * Default 0.10.
   */
  distractorMinGrounding?: number
  /** Jaccard floor for chunk↔chunk linkage. Default 0.12. */
  linkMinJaccard?: number
  /**
   * Token-count gate for the Auto strategy's passthrough decision.
   * Default 1500.
   */
  autoPassthroughMaxTokens?: number
  /** Cosine ceiling above which a chunk is treated as redundant. Default 0.92. */
  redundancyMaxCosine?: number
}
/**
 * Assemble the reasoning context from caller-supplied retrieved chunks
 * (skip RedHop's chunking + retrieval and use it only for the final
 * allocation step). Returns the same `BuiltContext` shape as
 * `Document.context()`.
 */
export declare function buildContext(query: string, retrievedChunks: Array<ChunkInput>, options?: ContextOptions | undefined | null): BuiltContext
/**
 * Distractor-only filter (no budget truncation): keep everything above the
 * grounding bar, drop only the off-topic chunks. Returns a `BuiltContext`
 * whose `text` / `chunks` / `citations` reflect the filtered set.
 */
export declare function filterContext(query: string, retrievedChunks: Array<ChunkInput>, options?: ContextOptions | undefined | null): BuiltContext
/**
 * Pure diagnostics over caller-supplied chunks: what would RedHop do, and
 * why, without paying the assembly cost. Returns the same `Report` shape
 * as `Document.context().report`.
 *
 * Like Python's `redhop.analyze_context`, this is a "no-budget" surface —
 * the `token_budget` option, if supplied, is ignored so the report's
 * `budget_utilization` reflects pure-analysis semantics (all chunks
 * counted) and stays consistent across bindings.
 */
export declare function analyzeContext(query: string, retrievedChunks: Array<ChunkInput>, options?: ContextOptions | undefined | null): Report
/**
 * Token economics over caller-supplied chunks (evidence density, distractor
 * ratio, redundancy, estimated wasted tokens). Returns a JSON string —
 * callers `JSON.parse()` for the typed shape.
 *
 * Like Python's `redhop.context_economics`, this is a "no-budget" surface
 * — the `token_budget` option is ignored so `budget_utilization` is
 * computed against an unbounded budget (essentially 0), matching the
 * "pure analysis, no filtering, no truncation" intent.
 */
export declare function contextEconomics(query: string, retrievedChunks: Array<ChunkInput>, options?: ContextOptions | undefined | null): string
/**
 * The assembled context: prompt string, selected chunks, citations, report.
 *
 * Class (not plain object) so it can hold the underlying Rust `BuiltContext`
 * for in-process operations like [`evaluate`]. All four existing fields
 * (`text`, `chunks`, `citations`, `report`) remain accessible as JS
 * properties via getters.
 */
export declare class BuiltContext {
  /** The assembled context as a single prompt string (drop-in for `llm.generate`). */
  get text(): string
  /** Selected chunks in presentation order, as plain strings. */
  get chunks(): Array<string>
  /** Per-chunk provenance — source, page, heading, line, text. */
  get citations(): Array<Citation>
  /** The Decision Report: what was kept, what was dropped, why. */
  get report(): Report
}
/**
 * A document you reason over. RedHop owns chunking, internal retrieval, and
 * reasoning-preserving context allocation; you think in documents and queries.
 */
export declare class Document {
  /** Build from raw text you already have. */
  static fromText(text: string, options?: Options | undefined | null): Document
  /** Build from chunks you already produced (array of strings). */
  static fromChunks(chunks: Array<string>, options?: Options | undefined | null): Document
  /** Build straight from a file on disk — PDF, DOCX, PPTX, XLSX, or text/code. */
  static fromFile(path: string, options?: Options | undefined | null): Document
  /**
   * Build from in-memory bytes you fetched (S3 / GCS / Azure Blob / HTTP / DB).
   * `source` (e.g. `"contract.pdf"`) picks the parser and is the citation source.
   */
  static fromBytes(data: Buffer, source: string, options?: Options | undefined | null): Document
  /**
   * Build one index from every readable file in a folder. Honors `.gitignore` +
   * `ignore` globs; `persist: true` saves an incremental on-disk index.
   */
  static fromFolder(path: string, options?: FolderOptions | undefined | null): Document
  /** Number of chunks the document holds. */
  get chunkCount(): number
  /**
   * Number of source files indexed into this Document. `1` for the
   * single-source constructors (`fromText`, `fromFile`, `fromBytes`,
   * `fromChunks`); the readable file count for `fromFolder` (excludes
   * `skippedFiles`).
   */
  get nFiles(): number
  /**
   * Files that `fromFolder` skipped, as `{ source, reason }` objects —
   * unsupported formats, unreadable bytes, no extractable text (e.g.
   * scanned PDFs without OCR), etc. Empty array for single-source
   * constructors.
   */
  get skippedFiles(): Array<SkippedFile>
  /**
   * Assemble the reasoning context for a query (retrieve → allocate).
   * `neighbors` / `includeHeading` add structural context expansion.
   */
  context(query: string, budget?: number | undefined | null, neighbors?: number | undefined | null, includeHeading?: boolean | undefined | null): BuiltContext
  /**
   * Pure diagnostics: retrieve + score for the query but DON'T assemble
   * the prompt. Returns the same `Report` shape as `context().report` so
   * callers can audit what would happen without paying assembly cost or
   * stringifying the chunks.
   */
  analyze(query: string): Report
}
