/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Chunking / assembly / retrieval options for the `Document.from*` constructors.
 * Every field is optional; omit for evidence-backed defaults.
 */
export interface Options {
  /** Source label for `fromText` (default `"document"`). */
  source?: string
  /** Target tokens per chunk (index-time). Default 128. */
  chunkSize?: number
  /** Sentences of overlap between adjacent chunks. Default 1. */
  chunkOverlap?: number
  /** Default assembly token budget (override per call). Default 8192. */
  tokenBudget?: number
  /** Candidates to retrieve before assembly. Default 20. */
  candidateK?: number
  /**
   * Assembly strategy: `auto` (default) · `reasoning_preserving` ·
   * `distractor_filtered` · `redundancy_pruned` · `max_density` · `raw_topk`.
   */
  strategy?: string
  /** `"lexical"` (default, BM25), `"hybrid"`, or `"semantic"`. */
  retrieval?: string
  /** Built-in embedding model to download (`"bge-small"` / `"bge-base"`). */
  model?: string
  /** Advanced: path to a local ONNX embedding model. */
  embedderModel?: string
  /** Advanced: path to its tokenizer. */
  embedderTokenizer?: string
  /** Advanced: the model's output dimension. Default 384. */
  embedderDim?: number
  /** Advanced: `"cls"` (default) or `"mean"`. */
  embedderPooling?: string
  /** Advanced: query prefix for asymmetric models (E5: `"query: "`). */
  embedderQueryPrefix?: string
  /** Advanced: passage prefix for asymmetric models (E5: `"passage: "`). */
  embedderPassagePrefix?: string
  /** Hybrid BM25 prune depth. Default 50. */
  candidatePool?: number
  /**
   * Optional second-stage cross-encoder reranker by name (`"cross-encoder"`,
   * auto-downloaded). Reorders the candidate pool by jointly scoring each
   * `(query, passage)` pair. Works under any retrieval tier.
   */
  rerank?: string
  /**
   * Floor on the number of candidates delivered to the assembler. Under
   * `"hybrid"` / `"semantic"` retrieval, if the primary tier returns
   * fewer, a BM25 fallback tops the result up to this number. Default
   * `0` (off). No effect under `"lexical"`. Pair with
   * `report.lowConfidenceRetrieval` to detect a weak-fallback case.
   */
  minCandidates?: number
  /**
   * Lexical analyzer language. Drives both BM25 retrieval and the
   * grounding scorer's term extraction so the two layers agree on what
   * counts as "the same term" (English `compression` finds `compress`,
   * German `Bücher` finds `Buch`, etc.). Default `"english"`.
   *
   * Supported: `"arabic"`, `"danish"`, `"dutch"`, `"english"`,
   * `"finnish"`, `"french"`, `"german"`, `"greek"`, `"hungarian"`,
   * `"italian"`, `"norwegian"`, `"portuguese"`, `"romanian"`,
   * `"russian"`, `"spanish"`, `"swedish"`, `"tamil"`, `"turkish"` —
   * the 18 Snowball Porter2 languages. Unknown strings ERROR (we
   * don't silently fall back to English; a typo'd `"germann"` should
   * surface).
   */
  language?: string
}
/** Extra options for `Document.fromFolder` (plus the chunking/retrieval `options`). */
export interface FolderOptions {
  /** Recurse into subdirectories. Default true. */
  recursive?: boolean
  /** Honor `.gitignore`. Default true. */
  gitignore?: boolean
  /** Extra gitignore-style globs to exclude, e.g. `["*.lock", "tests/**"]`. */
  ignore?: Array<string>
  /** Persist the index to disk and reload it incrementally on the next run. */
  persist?: boolean
  /** Where the persisted index lives (default `<folder>/.redhop`). */
  indexDir?: string
  /** Chunking / retrieval options (same fields as the other constructors). */
  options?: Options
}
/** Where one selected chunk came from — for citing the evidence. */
export interface Citation {
  source: string
  page?: number
  heading?: string
  line?: number
  text: string
}
/** The Decision Report: what the assembly did, and why. */
export interface Report {
  /** `"passthrough"` | `"prune"` | `"not_auto"`. */
  autoDecision: string
  totalTokens: number
  retainedEvidenceRatio: number
  secondHopRescues: number
  /** Structural-expansion chunks added (neighbors / headings). */
  nExpanded: number
  /**
   * `true` when nothing in the assembled context was above the grounding
   * floor — the query may share little vocabulary with the corpus.
   */
  lowConfidenceRetrieval: boolean
  /** The grounding ceiling that `low_confidence_retrieval` applied. */
  lowConfidenceThreshold: number
  /** The human-readable Decision Report. */
  rendered: string
}
/** A file that `Document.fromFolder` skipped, with the reason why. */
export interface SkippedFile {
  /** Source path of the file that was skipped. */
  source: string
  /**
   * Human-readable reason: unsupported format, unreadable bytes, no
   * extractable text, etc.
   */
  reason: string
}
/** The assembled context: prompt string, selected chunks, citations, report. */
export interface BuiltContext {
  text: string
  chunks: Array<string>
  citations: Array<Citation>
  report: Report
}
/**
 * A document you reason over. RedHop owns chunking, internal retrieval, and
 * reasoning-preserving context allocation; you think in documents and queries.
 */
export declare class Document {
  /** Build from raw text you already have. */
  static fromText(text: string, options?: Options | undefined | null): Document
  /** Build from chunks you already produced (array of strings). */
  static fromChunks(chunks: Array<string>, options?: Options | undefined | null): Document
  /** Build straight from a file on disk — PDF, DOCX, PPTX, XLSX, or text/code. */
  static fromFile(path: string, options?: Options | undefined | null): Document
  /**
   * Build from in-memory bytes you fetched (S3 / GCS / Azure Blob / HTTP / DB).
   * `source` (e.g. `"contract.pdf"`) picks the parser and is the citation source.
   */
  static fromBytes(data: Buffer, source: string, options?: Options | undefined | null): Document
  /**
   * Build one index from every readable file in a folder. Honors `.gitignore` +
   * `ignore` globs; `persist: true` saves an incremental on-disk index.
   */
  static fromFolder(path: string, options?: FolderOptions | undefined | null): Document
  /** Number of chunks the document holds. */
  get chunkCount(): number
  /**
   * Number of source files indexed into this Document. `1` for the
   * single-source constructors (`fromText`, `fromFile`, `fromBytes`,
   * `fromChunks`); the readable file count for `fromFolder` (excludes
   * `skippedFiles`).
   */
  get nFiles(): number
  /**
   * Files that `fromFolder` skipped, as `{ source, reason }` objects —
   * unsupported formats, unreadable bytes, no extractable text (e.g.
   * scanned PDFs without OCR), etc. Empty array for single-source
   * constructors.
   */
  get skippedFiles(): Array<SkippedFile>
  /**
   * Assemble the reasoning context for a query (retrieve → allocate).
   * `neighbors` / `includeHeading` add structural context expansion.
   */
  context(query: string, budget?: number | undefined | null, neighbors?: number | undefined | null, includeHeading?: boolean | undefined | null): BuiltContext
  /**
   * Pure diagnostics: retrieve + score for the query but DON'T assemble
   * the prompt. Returns the same `Report` shape as `context().report` so
   * callers can audit what would happen without paying assembly cost or
   * stringifying the chunks.
   */
  analyze(query: string): Report
}
